server:
  port: 9091


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  application:
    name: library
  jpa:
    show-sql: false
